// app/legal/mls/page.tsx
import { Metadata } from "next";

// Brand palette (from your homepage)
const C = {
  cream:        "#EFEAE0",
  creamWarm:    "#F4F0E8",
  bgCard:       "#FAF7F0",
  forest:       "#1F3D2E",
  forestDeep:   "#14271E",
  moss:         "#4A6B53",
  gold:         "#B89968",
  goldDeep:     "#9A7E50",
  goldSoft:     "#D9C49C",
  ink:          "#14271E",
  inkSoft:      "#4A6B53",
  muted:        "rgba(20,39,30,0.55)",
  border:       "rgba(20,39,30,0.10)",
  borderDark:   "rgba(244,240,232,0.12)",
  creamText:    "rgba(244,240,232,0.78)",
  creamMuted:   "rgba(244,240,232,0.55)",
  creamDim:     "rgba(244,240,232,0.70)",
};

const CONTENT = "mx-auto w-full max-w-[1280px] px-6 lg:px-12";

export const metadata: Metadata = {
  title: "MLS Compliance | Metes",
  description: "Important disclaimers for MLS compliance.",
};

export default function MLSCompliancePage() {
  return (
    <div className={CONTENT}>
      <div style={{
        background: C.bgCard,
        borderRadius: "14px",
        padding: "48px 40px",
        border: `1px solid ${C.border}`
      }}>
        <h1 style={{
          fontFamily: "var(--font-manrope, sans-serif)",
          fontWeight: 500,
          fontSize: "clamp(28px, 4vw, 48px)",
          lineHeight: 1.06,
          letterSpacing: "-0.015em",
          color: C.forest,
          marginBottom: "24px"
        }}>
          Legal & Compliance Disclosure
        </h1>

        <p style={{
          fontSize: "clamp(14px, 1.2vw, 16px)",
          lineHeight: 1.6,
          color: C.inkSoft,
          marginBottom: "32px"
        }}>
          Metes provides AI-powered productivity tools designed to assist real estate professionals in generating marketing content, organizing property media, and auditing listing drafts for common regulatory risks. By using the Metes platform, you acknowledge and agree to the terms and limitations outlined below.
        </p>

        <div style={{
          display: "flex",
          flexDirection: "column",
          gap: "32px"
        }}>
          <section>
            <h2 style={{
              fontFamily: "var(--font-manrope, sans-serif)",
              fontWeight: 700,
              fontSize: "20px",
              color: C.forest,
              marginBottom: "16px"
            }}>
              1. Not Legal or Professional Advice
            </h2>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft
            }}>
              Metes is an artificial intelligence assistant, not a law firm, a regulatory body, or a licensed real estate brokerage. The information and content generated by our platform—including Fair Housing Act (FHA) audits, property descriptions, and neighborhood guides—are provided for informational and organizational purposes only.
            </p>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft,
              marginTop: "12px"
            }}>
              Nothing produced by Metes should be construed as legal advice, a formal compliance audit, or a guarantee of suitability for any specific Multiple Listing Service (MLS).
            </p>
          </section>

          <section>
            <h2 style={{
              fontFamily: "var(--font-manrope, sans-serif)",
              fontWeight: 700,
              fontSize: "20px",
              color: C.forest,
              marginBottom: "16px"
            }}>
              2. Fair Housing Act (FHA) Compliance
            </h2>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft
            }}>
              Metes utilizes advanced algorithms to identify and flag language that may carry a high risk of violating the Fair Housing Act (FHA). While we strive for 100% accuracy in our risk detection, AI models are non-deterministic and may occasionally miss nuanced violations or flag compliant language as a risk.
            </p>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft,
              marginTop: "12px"
            }}>
              The licensed real estate professional remains the final authority on all advertising. It is your sole responsibility to ensure that all marketing materials disseminated via the MLS, social media, or email are fully compliant with federal, state, and local Fair Housing laws.
            </p>
          </section>

          <section>
            <h2 style={{
              fontFamily: "var(--font-manrope, sans-serif)",
              fontWeight: 700,
              fontSize: "20px",
              color: C.forest,
              marginBottom: "16px"
            }}>
              3. Factual Accuracy & MLS Rules
            </h2>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft
            }}>
              Metes generates property descriptions and neighborhood insights based on user-provided notes and third-party data (such as the Google Places API).
            </p>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft,
              marginTop: "12px"
            }}>
              <strong>Verification:</strong> You are responsible for verifying all factual claims (e.g., square footage, room counts, proximity to amenities) before publication.
            </p>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft,
              marginTop: "12px"
            }}>
              <strong>MLS Specificity:</strong> Every MLS has unique rules regarding character counts, forbidden words, and branding. You must review all Metes output to ensure it meets the specific requirements of your local board.
            </p>
          </section>

          <section>
            <h2 style={{
              fontFamily: "var(--font-manrope, sans-serif)",
              fontWeight: 700,
              fontSize: "20px",
              color: C.forest,
              marginBottom: "16px"
            }}>
              4. Limitation of Liability
            </h2>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft
            }}>
              Metes, its founders, and its affiliates shall not be held liable for any fines, legal fees, listing rejections, or loss of license resulting from the use of content generated by this platform. By using Metes, you accept all risks associated with the publication of AI-assisted marketing materials.
            </p>
          </section>

          <section>
            <h2 style={{
              fontFamily: "var(--font-manrope, sans-serif)",
              fontWeight: 700,
              fontSize: "20px",
              color: C.forest,
              marginBottom: "16px"
            }}>
              5. Professional Review Requirement
            </h2>
            <p style={{
              fontSize: "14px",
              lineHeight: 1.6,
              color: C.inkSoft
            }}>
              Our "Human-in-the-Loop" (HITL) philosophy requires that an agent reviews and approves all data before it is finalized. Do not publish any Metes-generated content without a thorough human review for accuracy, tone, and legal compliance.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}