import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, MapPin, Compass, Sparkles } from "lucide-react";
import Footer from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Neighborhood Description Examples for MLS Listings: 12 Markets | Metes",
  description:
    "Twelve neighborhood description examples across distinct property contexts — college-town, mountain-outdoor, historic, suburban, 55+, working waterfront — with the framework for writing strong neighborhood content.",
  keywords: [
    "neighborhood description examples",
    "neighborhood description for real estate listing",
    "mls neighborhood description",
    "how to write neighborhood description",
    "real estate listing neighborhood",
    "neighborhood description template",
    "describing neighborhood mls listing",
    "fair housing neighborhood description",
  ],
  alternates: {
    canonical: "https://www.metes.app/learn/neighborhood-description-examples",
  },
  openGraph: {
    title: "Neighborhood Description Examples for MLS Listings: 12 Markets",
    description:
      "Twelve neighborhood examples across distinct property contexts. The framework for writing strong neighborhood content for any listing.",
    url: "https://www.metes.app/learn/neighborhood-description-examples",
    siteName: "Metes",
    type: "article",
    images: [
      {
        url: "https://www.metes.app/og/neighborhood-description-examples.png",
        width: 1200,
        height: 630,
        alt: "Neighborhood description examples for MLS listings",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Neighborhood Description Examples for MLS Listings",
    description: "Twelve examples and the framework for writing neighborhood content for any listing.",
    images: ["https://www.metes.app/og/neighborhood-description-examples.png"],
  },
  robots: { index: true, follow: true },
};

const SCHEMA_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      "@id": "https://www.metes.app/learn/neighborhood-description-examples#article",
      "headline": "Neighborhood Description Examples for MLS Listings: 12 Markets, One Framework",
      "description":
        "Twelve neighborhood description examples across distinct property contexts. Each generated by Metes using live Google Places API data, edited lightly for voice.",
      "image": "https://www.metes.app/og/neighborhood-description-examples.png",
      "datePublished": "2026-06-22",
      "dateModified": "2026-06-22",
      "author": {
        "@type": "Organization",
        "name": "Metes Editorial",
        "url": "https://www.metes.app",
      },
      "publisher": {
        "@type": "Organization",
        "name": "Metes",
        "url": "https://www.metes.app",
        "logo": {
          "@type": "ImageObject",
          "url": "https://www.metes.app/logo.png",
        },
      },
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://www.metes.app/learn/neighborhood-description-examples",
      },
      "keywords":
        "neighborhood description, MLS listing, real estate writing, Fair Housing, Google Places API, lifestyle marketing",
    },
    {
      "@type": "FAQPage",
      "@id": "https://www.metes.app/learn/neighborhood-description-examples#faq",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "How long should a neighborhood description be?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "There's no fixed length. A neighborhood section within an MLS description typically runs 75-150 words; a standalone neighborhood guide on a listing page or microsite can run 300-500 words. The principle is the same: every sentence should add specific information. If a sentence could describe any neighborhood, it shouldn't be in the description.",
          },
        },
        {
          "@type": "Question",
          "name": "What should I include in a neighborhood description for an MLS listing?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The strongest neighborhood descriptions reference 3-5 specific named places (coffee shops, restaurants, parks, stores), 1-2 outdoor or recreation features, and any specific lifestyle texture that makes the neighborhood distinctive. Skip generic adjectives like 'vibrant,' 'welcoming,' or 'family-oriented' — they don't add information and 'family-oriented' specifically violates Fair Housing rules.",
          },
        },
        {
          "@type": "Question",
          "name": "What words to avoid in neighborhood descriptions?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "HUD-flagged language to avoid includes: 'perfect for families,' 'great for young professionals,' 'family-friendly,' 'walking distance' as a general descriptor without specific distance, 'safe neighborhood,' 'quiet' as a coded character descriptor, 'exclusive,' and others. First-offense civil penalty for Fair Housing violations is $25,597.",
          },
        },
        {
          "@type": "Question",
          "name": "Should I describe schools in MLS listings?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Per HUD's April 2026 Dear Colleague letter, agents may share factual school information (district names, ratings from sources like GreatSchools) with buyers, as long as the information is shared consistently and not used to direct buyers toward or away from neighborhoods based on protected class characteristics. Subjective descriptors like 'top schools' remain risky; specific data points (GreatSchools rating, district name) are safer.",
          },
        },
        {
          "@type": "Question",
          "name": "Should I name local businesses in listing descriptions?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes — naming specific businesses is generally safe and strongly improves the quality of neighborhood writing. The constraints: the businesses should actually exist (no fabrication), they should genuinely be near the property, and the descriptions should be factual rather than promotional. 'Whole Foods Market' is fine; 'the best grocery store in the area' is subjective and weaker.",
          },
        },
        {
          "@type": "Question",
          "name": "How is writing about a small town different from writing about a city?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Smaller markets typically have lower commercial density, which means fewer named places to anchor the description. The strong move is to write fewer places more deeply rather than padding the description with thin mentions. A single well-described local institution is stronger than a list of five generic descriptors. Also: in smaller markets, mentioning context (the named neighborhood, the named region) carries more weight because readers may be evaluating the area from out of state.",
          },
        },
        {
          "@type": "Question",
          "name": "Can AI write neighborhood descriptions accurately?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "AI tools that work from training data alone (general-purpose tools like ChatGPT) routinely fabricate local businesses, parks, and amenities. Real-world LLM hallucination rates run 31.4% in complex domains. Tools that constrain the LLM to verified data sources (like the Google Places API) produce materially more accurate output. AI-generated neighborhood content has come a long way, but it benefits from light editorial polish to remove generic AI prose patterns.",
          },
        },
        {
          "@type": "Question",
          "name": "What's the Fair Housing rule for neighborhood descriptions?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The Fair Housing Act prohibits language in real estate advertising that indicates preference based on race, color, religion, sex, familial status, disability, or national origin. For neighborhood descriptions specifically, the most common violations involve familial status ('perfect for families') and disability ('walking distance'). The April 2026 HUD guidance clarified that factual school and crime data may be shared consistently.",
          },
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────
// Brand palette
// ─────────────────────────────────────────────────────────────────

const C = {
  cream: "#EFEAE0",
  creamWarm: "#F4F0E8",
  bgCard: "#FAF7F0",
  forest: "#1F3D2E",
  forestDeep: "#14271E",
  moss: "#4A6B53",
  gold: "#B89968",
  goldDeep: "#9A7E50",
  goldSoft: "#D9C49C",
  ink: "#14271E",
  inkSoft: "#4A6B53",
  muted: "rgba(20,39,30,0.55)",
  border: "rgba(20,39,30,0.10)",
};

// ─────────────────────────────────────────────────────────────────
// SectionLabel
// ─────────────────────────────────────────────────────────────────

function SectionLabel({ children, light = false }: { children: React.ReactNode; light?: boolean }) {
  return (
    <div className={`mb-4 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] ${light ? "text-[#D9C49C]" : "text-[#9A7E50]"}`}>
      <span className={`inline-block h-px w-[18px] ${light ? "bg-[#D9C49C]" : "bg-[#9A7E50]"}`} />
      {children}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// BulletList — gold bullets, matches Week 1 + Week 2 convention
// ─────────────────────────────────────────────────────────────────

function BulletList({ items }: { items: React.ReactNode[] }) {
  return (
    <ul style={{ listStyle: "none", padding: 0, margin: "0 0 16px 0", display: "flex", flexDirection: "column", gap: "10px" }}>
      {items.map((item, i) => (
        <li
          key={i}
          style={{
            paddingLeft: "20px",
            position: "relative",
            fontFamily: "var(--font-manrope, sans-serif)",
            fontSize: "16px",
            lineHeight: 1.7,
            color: C.ink,
          }}
        >
          <span style={{ position: "absolute", left: "4px", color: C.gold, fontWeight: 600 }}>•</span>
          {item}
        </li>
      ))}
    </ul>
  );
}

// ─────────────────────────────────────────────────────────────────
// Market data
// ─────────────────────────────────────────────────────────────────

interface PlaceItem {
  name: string;
  description: string;
}

interface MarketCategory {
  title: string;
  items: PlaceItem[];
}

interface Market {
  number: number;
  slug: string;
  name: string;
  subtitle: string;
  challenge: string;
  description: React.ReactNode;
  categories: MarketCategory[];
  doesWell: string;
  pushFurther: string;
}

const MARKETS: Market[] = [
  {
    number: 1,
    slug: "briar-chapel",
    name: "Briar Chapel, Chapel Hill, NC",
    subtitle: "the master-planned-near-college-town",
    challenge: "Briar Chapel sits in Chatham County south of Chapel Hill proper. The neighborhood story isn't \"walking distance to UNC\" — it's \"master-planned community with greenways and trails, with access to Chapel Hill culture nearby.\" Getting that right means resisting the easy story (Chapel Hill = college town) and writing what's actually true.",
    description: (
      <>Morning coffee at The Belted Goat, weekly produce runs at the Fearrington Farmers&apos; Market, weekend trail walks at Great Meadow Park. This is a community built around its greenways and local rituals — Fearrington Village provides the destination dining moment, and The Parlour at Manns Chapel anchors the wellness routine.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "The Belted Goat", description: "morning coffee and prepared provisions" },
          { name: "Fearrington Farmers' Market", description: "weekly source for produce from regional growers" },
          { name: "501 Pharmacy", description: "local pharmacy known for attentive service" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Great Meadow Park", description: "trails and open space, the centerpiece of the community's outdoor life" },
          { name: "The Park at Briar Chapel", description: "community park within the neighborhood itself" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Fearrington Village", description: "the destination meal, set in a landmark restored village" },
          { name: "Szechuan Village", description: "neighborhood Chinese, well-regarded locally" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "The Parlour at Manns Chapel", description: "yoga studio" },
          { name: "O2 Fitness", description: "regional fitness chain with a Chapel Hill area location" },
        ],
      },
    ],
    doesWell: "Names real places without exaggeration. Captures the \"Fearrington Village as anchor\" character that distinguishes Briar Chapel from a generic Carolina suburb. Doesn't oversell the Chapel Hill proximity.",
    pushFurther: "The Belted Goat description could reference what makes that specific spot work (it's inside a Fearrington Village building, which adds atmosphere). The Parlour at Manns Chapel benefits from the actual location naming — Manns Chapel Road is a specific Briar Chapel landmark, not just a road name.",
  },
  {
    number: 2,
    slug: "highland-park",
    name: "Highland Park, TX",
    subtitle: "the established affluent suburban",
    challenge: "Highland Park is the original wealth-suburb of Dallas, dating back to the 1910s, with deeply established institutions and a specific cultural identity. The risk is writing it as generic \"upscale neighborhood\" when its character is actually quite specific.",
    description: (
      <>The Highland Park routine runs on settled rhythms — coffee in the morning, the St. Michael&apos;s Farmers Market on Saturdays, the Teddy Bear Statues at Lakeside Park for afternoon walks. Dinner happens at Katy Trail Ice House when it&apos;s casual, somewhere more formal when it&apos;s not. The everyday infrastructure — Whole Foods, Trader Joe&apos;s, Eatzi&apos;s — sits within easy distance.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Whole Foods Market", description: "premium grocer for daily essentials" },
          { name: "Trader Joe's", description: "neighborhood favorite for the weekly shop" },
          { name: "Eatzi's Market & Bakery", description: "European-style market with chef-prepared meals" },
          { name: "St. Michael's Farmers Market", description: "Saturday morning institution" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Teddy Bear Statues in Lakeside Park", description: "landmark Highland Park park" },
          { name: "Reverchon Park", description: "paved paths and shaded routes nearby" },
          { name: "George W. Bush Presidential Center", description: "landscaped grounds open for walking" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Katy Trail Ice House", description: "outdoor beer garden, the casual Dallas standard" },
          { name: "San Martin Bakery and Restaurant", description: "pastries, hearty meals" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "Equinox Highland Park", description: "the destination fitness club" },
          { name: "Black Swan Yoga - Lovers", description: "community-focused yoga" },
          { name: "RITUAL ONE", description: "modern movement studio" },
        ],
      },
    ],
    doesWell: "Captures Highland Park's specific institutional density. The Teddy Bear Statues are a real landmark — most Highland Park residents could tell you where they are. Equinox plus the smaller studios shows the range of the wellness ecosystem.",
    pushFurther: "The \"settled rhythms\" framing risks reading as condescending if a reader hears \"the wealthy never change.\" Real Highland Park residents do change their routines; the framing could lead with what makes those rhythms appealing rather than naming them as fixed.",
  },
  {
    number: 3,
    slug: "ne-portland",
    name: "NE Portland, OR",
    subtitle: "the urban revitalized walkable",
    challenge: "NE Portland (Alberta Arts, Concordia) has been steadily transforming for two decades — from a historically Black neighborhood with deep cultural roots through gentrification to its current state as one of Portland's most active food-and-coffee districts. Writing about it requires acknowledging the food culture without pretending the area appeared yesterday.",
    description: (
      <>Mornings start with a pour-over at Proud Mary Cafe or chai and doughnuts at Pip&apos;s Original. Weekends mean the Hollywood Farmers Market, walks through Irving Park or Alberta Park, and dinner at McMenamins Kennedy School (a former elementary school converted into a dining-and-events landmark). Tin Shed Garden Cafe handles the brunch overflow.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Pip's Original Doughnuts & Chai", description: "handcrafted mini doughnuts and house-made chai, a Portland institution" },
          { name: "Proud Mary Cafe", description: "Australian-style roasting, technical brewing" },
          { name: "Hollywood Farmers Market", description: "weekly market for regional producers" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Irving Park", description: "broad lawns and mature trees" },
          { name: "Alberta Park", description: "paved walking paths" },
          { name: "Wilshire Park", description: "wooded trails" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "McMenamins Kennedy School", description: "the converted elementary school, now hotel, restaurant, theater, brewery" },
          { name: "Tin Shed Garden Cafe", description: "patio brunch, hearty plates" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "Forge Hot Yoga Alberta District", description: "heated yoga, modern studio" },
          { name: "The People's Yoga", description: "community-oriented practice" },
        ],
      },
    ],
    doesWell: "Names the specific Portland identities of named businesses (Pip's is a known Portland chai destination, Proud Mary's Australian roasting heritage is real and specific). The McMenamins Kennedy School description doesn't undersell its multi-purpose character.",
    pushFurther: "The Alberta neighborhood's specific cultural history could be acknowledged with more care — and would likely be inappropriate to do in a listing description anyway. The neighborhood guide stays in safe territory by focusing on the active food culture.",
  },
  {
    number: 4,
    slug: "asheville",
    name: "Asheville, NC",
    subtitle: "the mountain town with food culture",
    challenge: "Asheville's identity is mountain town + Blue Ridge views + a famously dense food and brewery scene. The neighborhood description needs to capture the food culture without leaning on the mountain-town generics (\"nestled in the Blue Ridge\"). The address (115 Oakland Rd) sits north of downtown, in the older residential stretch.",
    description: (
      <>Mornings begin at All Day Darling for brunch or Flour for pastries. The weekend routine runs through the Asheville City Market for produce and Pack Square Park for the downtown moment. Carrier Park handles longer outdoor sessions with river access. Dinner pulls from a deep bench — Chai Pani for South Indian street food, Pack&apos;s Tavern for the longer evening.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "All Day Darling", description: "craft coffee and seasonal brunch" },
          { name: "Flour", description: "artisan bakery, pastries" },
          { name: "Whole Foods Market", description: "the grocery default" },
          { name: "Asheville City Market", description: "weekly regional farmers market" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Pack Square Park", description: "downtown park, community events" },
          { name: "Carrier Park", description: "sports facilities, river access, paved paths" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Chai Pani Asheville", description: "celebrated Indian street food, James Beard recognition" },
          { name: "Pack's Tavern", description: "local institution, broad menu" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "Asheville Yoga Center", description: "long-running studio" },
          { name: "Cultivate Climbing - The Bunker", description: "climbing gym with community focus" },
        ],
      },
    ],
    doesWell: "The dining section earns its language — Chai Pani is genuinely well-known beyond Asheville, and pointing at that fact grounds the description in real recognition. The morning + weekend + dinner structure mirrors how buyers actually evaluate a neighborhood's lifestyle.",
    pushFurther: "No mention of the mountain context, which is what most non-Asheville buyers associate with the city. A polished version might add a single sentence about proximity to the Blue Ridge Parkway or a specific overlook — but doing so requires confidence the listing's location actually supports that claim.",
  },
  {
    number: 5,
    slug: "charleston",
    name: "Charleston Historic District, SC",
    subtitle: "the preserved historic",
    challenge: "Charleston's downtown peninsula has a tightly preserved historic character — the antebellum architecture, the church spires, the carriage tours. The risk in describing it: leaning on the obvious (history, charm) without naming the specific places that make daily life here distinct.",
    description: (
      <>Daily life on Chapel Street is grounded in Charleston&apos;s classic lifestyle. Mornings might start with bagels at Holey City Bagels or coffee at babas on cannon. Saturdays mean the Charleston Farmers Market. Afternoons run through the historic green of White Point Garden or along the waterfront at Waterfront Park, where the pineapple fountain marks the harbor&apos;s edge. Dinner pulls from a deep bench — Lewis Barbecue for Texas-style smoke, Fleet Landing for the river view.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "babas on cannon", description: "coffee and small plates in a sleek space" },
          { name: "Holey City Bagels", description: "hand-rolled bagels, a morning ritual for many residents" },
          { name: "Charleston Farmers Market", description: "Saturday morning destination at Marion Square" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Waterfront Park", description: "harbor-front, the famous pineapple fountain, walking paths" },
          { name: "Hampton Park", description: "broader park space with seasonal flowers" },
          { name: "White Point Garden", description: "historic park at the peninsula's tip, oak trees, harbor views" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Lewis Barbecue Charleston", description: "Texas-style smoked meats, communal outdoor seating" },
          { name: "Fleet Landing Restaurant & Raw Bar", description: "waterfront seafood, Cooper River views" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "HYLO Fitness Charleston", description: "strength and conditioning" },
          { name: "Coastal Climbing Gym", description: "indoor climbing" },
          { name: "Salt Spa & Yoga", description: "restorative yoga and spa" },
        ],
      },
    ],
    doesWell: "Specific landmarks (pineapple fountain, White Point Garden) anchor the description in places residents and visitors actually recognize. Lewis Barbecue's Texas-style identity grounds the food descriptor in something concrete.",
    pushFurther: "The historic architectural character isn't named directly. A polished version could reference the specific architectural context (rainbow row, antebellum townhouses) without venturing into protected-class territory. Architecture is safe ground; demographic implication isn't.",
  },
  {
    number: 6,
    slug: "bozeman",
    name: "Bozeman, MT",
    subtitle: "the growing mountain town",
    challenge: "Bozeman is a growing mountain town with a specific cultural identity — Montana State University, gateway to Yellowstone, a strong outdoor culture, an increasingly known brewery scene. The risk: defaulting to generic \"mountain town\" copy without naming what makes Bozeman specifically Bozeman.",
    description: (
      <>The Bozeman routine balances downtown culture with quick access to the outdoors. Coffee at Feed Café in the morning, hikes up Peets Hill or out at Story Mill Park, evenings at Montana Ale Works for elevated pub food or Revelry for the longer dinner. The Bozeman Community Food Co-op handles the weekly grocery rhythm.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Feed Café", description: "coffee and breakfast, locally run" },
          { name: "Bozeman Community Food Co-op - West Main", description: "community-focused grocery" },
          { name: "Bozeman Farmers' Market", description: "weekly market featuring regional producers" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Peets Hill/Burke Park", description: "the close-in hike, panoramic Gallatin Valley views" },
          { name: "Story Mill Park", description: "restored wetlands, trails, open recreation space" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Montana Ale Works", description: "elevated pub fare, local beer selection" },
          { name: "Jam!", description: "creative breakfast and lunch" },
          { name: "Revelry", description: "modern dining with regional ingredients" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "Bend Beyond", description: "hot yoga and Inferno Pilates" },
          { name: "Spire Climbing + Fitness", description: "climbing facility with broad equipment" },
        ],
      },
    ],
    doesWell: "Peets Hill is specifically named for the views — and that's accurate, it's the close-in hike with the valley panorama. The dining tier structure (casual pub → creative brunch → modern dinner) reflects how Bozeman residents actually use their food scene.",
    pushFurther: "The Yellowstone proximity (~90 minutes south to the North Entrance at Gardiner) is the unmentioned story. So is MSU's influence on the town's character. A polished description might name one or both, with care about the exact distances and relationships.",
  },
  {
    number: 7,
    slug: "plano",
    name: "Plano, TX",
    subtitle: "the suburban planned community",
    challenge: "Plano is a Dallas-Fort Worth suburb with a tech-employer base (corporate campuses for Toyota, Liberty Mutual, FedEx, and others), strong public schools, and a deliberately planned street and park system. The risk: writing it as featureless suburbia when its specific character is the planned-suburb-done-well.",
    description: (
      <>Plano&apos;s daily routine balances trail-rich green space with the kind of corporate-and-cultural mix the suburb has built over decades. Coffee at Local Good or downtown at 1418 Coffee. Long walks through Oak Point Park and Nature Preserve. Sunday market runs at Mitsuwa for the Japanese pantry essentials. Haggard Park anchors the smaller-scale outdoor moments.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Local Good Coffee Co.", description: "independent neighborhood coffee" },
          { name: "1418 Coffee - Historic Downtown Plano", description: "downtown shop, the local-meeting standard" },
          { name: "Green Vine Market", description: "specialty market for curated goods" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Oak Point Park and Nature Preserve", description: "extensive trails, a Plano signature" },
          { name: "Haggard Park", description: "classic central park, walking paths" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Mitsuwa Marketplace - Plano", description: "Japanese market and food hall, a regional destination" },
        ],
      },
    ],
    doesWell: "Names Plano's specific assets (Mitsuwa, Oak Point Park) rather than generic-suburb features. The Mitsuwa mention is the specific identifier — Japanese supermarkets at this scale are uncommon outside major metros, and Mitsuwa-in-Plano is something residents actively reference.",
    pushFurther: "The corporate context (Plano is a major DFW employment hub) isn't named. A polished version might reference the broader corporate-and-cultural mix that makes Plano distinct from a typical North Texas suburb.",
  },
  {
    number: 8,
    slug: "brightmoor-detroit",
    name: "Brightmoor, Detroit, MI",
    subtitle: "the revitalizing urban",
    challenge: "Brightmoor sits in Far Northwest Detroit — a neighborhood that's been through population loss, vacancy, and an active grassroots revitalization (Brightmoor Maker Space, urban farms, community gardens). Writing about it honestly means neither overselling the food-and-coffee scene nor underselling the genuine community-led work happening.",
    description: (
      <>Brightmoor&apos;s daily rhythm runs on community staples. Detroit Brew-ti-ful Coffee House in the morning, weekend produce at the Northwest Detroit Farmers&apos; Market, walks through Eliza Howell Park with its river views and wooded trails. Sweet Potato Sensations is the dessert and comfort-food destination. Scotty Simpson&apos;s anchors the longer-running food traditions of the area.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Detroit Brew-ti-ful Coffee House", description: "locally run, locally roasted coffee" },
          { name: "Sweet Potato Sensations", description: "handcrafted sweets and savory comfort food, a Northwest Detroit institution" },
          { name: "Northwest Detroit Farmers' Market", description: "community-focused weekly market" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Eliza Howell Park", description: "wooded trails, river views, a substantial green space" },
          { name: "Stoepel Park", description: "open fields, neighborhood park" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Scotty Simpson's Fish & Chips", description: "long-running Detroit institution, classic fish and chips" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "JC Jones Bootcamp", description: "strength and endurance training" },
          { name: "Fit4Life Michigan", description: "personalized fitness programs" },
        ],
      },
    ],
    doesWell: "Sweet Potato Sensations as a \"Northwest Detroit institution\" is specifically true — it's been operating in the area for decades and is one of the named local landmarks. Scotty Simpson's is similarly real and specific. The output doesn't pretend Brightmoor is something it isn't.",
    pushFurther: "The community-led revitalization story (urban farms, the Brightmoor Maker Space) isn't named. Whether to reference it in a listing description depends on the property — for some buyers it's a feature, for others a complicating factor.",
  },
  {
    number: 9,
    slug: "the-villages",
    name: "The Villages, FL",
    subtitle: "the master-planned 55+",
    challenge: "The Villages is the largest age-restricted active-adult community in the country, with a specific lifestyle infrastructure (golf cart paths, town squares, country clubs). Fair Housing rules for 55+ housing are specific — describing the community accurately requires staying within HOPA-compliant language.",
    description: (
      <>Daily life centers on the community&apos;s planned infrastructure and easy access to local staples. Mornings at the Brown &amp; Brown Farms market for produce, afternoons at Mulberry Grove Dog Park, evenings at the Glenview Country Club or Francesco&apos;s. The neighborhood Publix sits at Mulberry Grove Plaza for the weekly groceries.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Publix Super Market at Mulberry Grove Plaza", description: "the everyday grocery" },
          { name: "Donna's Dream Cakes", description: "local bakery, custom creations" },
          { name: "Brown & Brown Farms and Country Store", description: "rustic market with fresh local produce" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Mulberry Grove Dog Park", description: "community dog park" },
          { name: "Doggie Doo Run Run", description: "second neighborhood dog park" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Glenview Country Club", description: "country club dining" },
          { name: "The Legacy Restaurant at Nancy Lopez Country Club", description: "dining with golf course views" },
          { name: "Francesco's Ristorante and Stone Fire Pizza", description: "Italian, hand-made pasta and stone-fired pizza" },
        ],
      },
    ],
    doesWell: "Stays in HOPA-compliant territory. The country club dining, the dog parks, and the produce market structure are accurate to the lifestyle without invoking age-restricted demographic language that creates Fair Housing exposure outside of HOPA-protected contexts.",
    pushFurther: "The output is thinner than other markets — fewer places named, more compact. The Villages has substantial commercial density at its town squares, and the API may not have surfaced everything available. A polished version could expand the country club and town square infrastructure with more specific anchor locations.",
  },
  {
    number: 10,
    slug: "lake-nona",
    name: "Lake Nona, Orlando, FL",
    subtitle: "the new master-planned",
    challenge: "Lake Nona is a relatively new master-planned community in southeast Orlando, built around medical and sports research campuses, with a deliberately modern infrastructure (Boxi Park, the Lake Nona Wave Hotel, integrated tech). The challenge: most neighborhood description templates assume older, settled communities. Lake Nona is contemporary by design.",
    description: (
      <>Lake Nona&apos;s daily rhythm runs on its built-in infrastructure. Mornings at Starbucks or Crumbl, afternoons at Heroes Community Park or Crescent Park, evenings at Boxi Park — the open-air food destination set in repurposed shipping containers. The Lake Nona Wave Hotel anchors the more sophisticated end of the dining scene. Publix at Lake Nona Plaza handles the weekly grocery rhythm.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Publix Super Market at Lake Nona Plaza", description: "the everyday grocery for fresh produce and pantry essentials" },
          { name: "Starbucks Coffee Company", description: "morning coffee or a quiet workspace" },
          { name: "Crumbl", description: "rotating gourmet cookies, afternoon treat" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Heroes Community Park", description: "expansive green space with fields and walking paths" },
          { name: "Crescent Park", description: "peaceful local park for short walks" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Boxi Park", description: "open-air destination with diverse food in a shipping-container setting" },
          { name: "Lake Nona Wave Hotel", description: "design-forward landmark with sophisticated dining" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "HILI FITNESS Lake Nona", description: "highly-rated training facility focused on personalized fitness" },
        ],
      },
    ],
    doesWell: "Names Lake Nona's signature design moments — Boxi Park's shipping-container concept and the Wave Hotel's architectural identity. These are specifically Lake Nona, not generic Florida-suburb features.",
    pushFurther: "Lake Nona's broader infrastructure story — the medical campuses, the autonomous shuttle, the focus on health and innovation — isn't named. A polished version could reference the community's intentional design without venturing into demographic territory.",
  },
  {
    number: 11,
    slug: "sun-city-west",
    name: "Sun City West, AZ",
    subtitle: "the established 55+",
    challenge: "Sun City West is one of Arizona's oldest active-adult communities (1978), with its own infrastructure (recreation centers, golf courses, club system). Writing it well requires staying within HOPA-compliant lifestyle language while capturing the community-anchored daily rhythm.",
    description: (
      <>Sun City West&apos;s daily rhythm runs on community-anchored routines. Mornings at the Wellphora farmers market for fresh local goods. Afternoon walks through Beardsley Park. Evenings at Briarwood Country Club for a formal meal or Hole &apos;n One for a classic breakfast plate. The recreation centers anchor the wellness routines, including yoga sessions at the Beardsley Recreation Center.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Wellphora", description: "local farmers market" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Beardsley Park", description: "outdoor space, manicured lawns and walking paths" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Briarwood Country Club", description: "country club dining" },
          { name: "Hole 'n One", description: "breakfast plates, casual comfort" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "Thrive Healing Center", description: "yoga focused on physical and mental well-being" },
          { name: "Beardsley Recreation Center Yoga Studio", description: "yoga within the community recreation center" },
        ],
      },
    ],
    doesWell: "Stays HOPA-safe. Names the community's recreation-center infrastructure, which is the actual lifestyle infrastructure of the community.",
    pushFurther: "This output is thinner than the others. Active-adult planned communities often have substantial internal infrastructure (golf, pickleball, club system, community theater) that the standard Places API query may not surface comprehensively. Polishing this kind of output requires either supplementing with verified community-provided amenities or framing the description around the residential character rather than commercial density.",
  },
  {
    number: 12,
    slug: "midtown-atlanta",
    name: "Midtown Atlanta, GA",
    subtitle: "the urban with green space",
    challenge: "Midtown Atlanta is dense urban with a real green-space anchor (Piedmont Park) and a distinct cultural identity (museums, the Fox Theatre, Georgia Tech adjacency). The description needs to capture the urban-but-with-park character that defines daily life here.",
    description: (
      <>Midtown&apos;s daily life pulls between the urban density and the green-space anchor at Piedmont Park. Mornings at Café Intermezzo (a late-night Midtown institution) or at the Beltline Shed at Ponce City Market for local goods. Weekends at Piedmont Park or along the Beltline. The Martin Luther King Jr. National Historical Park adds a different kind of green space — historical, contemplative — within easy distance.</>
    ),
    categories: [
      {
        title: "The Everyday",
        items: [
          { name: "Trader Joe's", description: "neighborhood grocery" },
          { name: "Café Intermezzo - Midtown", description: "European-style coffee house, late-night Midtown institution" },
          { name: "Beltline Shed at Ponce City Market", description: "open-air market along the Atlanta Beltline" },
        ],
      },
      {
        title: "Outdoor & Recreation",
        items: [
          { name: "Piedmont Park", description: "Atlanta's signature urban park, expansive lawns, skyline views" },
          { name: "Martin Luther King, Jr. National Historical Park", description: "historical green space, walking areas, monuments" },
        ],
      },
      {
        title: "Dining",
        items: [
          { name: "Hungry AF Downtown", description: "creative meals, casual setting" },
        ],
      },
      {
        title: "Wellness & Fitness",
        items: [
          { name: "CorePower Yoga - Atlanta Midtown", description: "heated yoga" },
          { name: "Highland Yoga - Virginia Highland", description: "power yoga, community-driven" },
          { name: "GA Tech Campus Recreation Center", description: "extensive fitness facility (Georgia Tech adjacency)" },
        ],
      },
    ],
    doesWell: "Specifically names Piedmont Park's role as the green anchor — Midtown's defining feature is the park, and the description leads with that. The Beltline reference is also specific and accurate.",
    pushFurther: "Café Intermezzo's late-night identity could be sold harder — it's one of the few late-night spots in Midtown that's been there for decades. The MLK National Historical Park inclusion is contextual; whether to reference depends on whether the listing is genuinely close enough to make that proximity meaningful.",
  },
];

// ─────────────────────────────────────────────────────────────────
// Style atoms
// ─────────────────────────────────────────────────────────────────

const h2Style = {
  fontFamily: "var(--font-manrope, sans-serif)",
  fontSize: "clamp(24px, 3.5vw, 36px)",
  fontWeight: 500 as const,
  lineHeight: 1.1,
  letterSpacing: "0.005em",
  color: C.ink,
  marginTop: 0,
  marginBottom: "24px",
};

const h3Style = {
  fontFamily: "var(--font-manrope, sans-serif)",
  fontSize: "clamp(18px, 2vw, 22px)",
  fontWeight: 600 as const,
  lineHeight: 1.25,
  letterSpacing: "-0.005em",
  color: C.ink,
  marginTop: "32px",
  marginBottom: "14px",
};

const h4Style = {
  fontFamily: "var(--font-manrope, sans-serif)",
  fontSize: "15px",
  fontWeight: 600 as const,
  lineHeight: 1.3,
  letterSpacing: "0.005em",
  color: C.goldDeep,
  marginTop: "20px",
  marginBottom: "8px",
  textTransform: "uppercase" as const,
};

const proseStyle = {
  fontFamily: "var(--font-manrope, sans-serif)",
  fontSize: "16px",
  lineHeight: 1.7,
  color: C.ink,
  marginBottom: "16px",
};

const CONTENT = "mx-auto w-full max-w-[960px] px-6 lg:px-8";
const READING = "mx-auto max-w-[720px]";

// ─────────────────────────────────────────────────────────────────
// Market block component
// ─────────────────────────────────────────────────────────────────

function MarketBlock({ market }: { market: Market }) {
  return (
    <div id={market.slug} style={{ marginBottom: "64px", scrollMarginTop: "24px" }}>
      <div className="mb-4 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-[#9A7E50]">
        <span className="inline-block h-px w-[18px] bg-[#9A7E50]" />
        Market {market.number}
      </div>

      <h3 style={{
        fontFamily: "var(--font-manrope, sans-serif)",
        fontSize: "clamp(22px, 2.6vw, 28px)",
        fontWeight: 500,
        lineHeight: 1.15,
        color: C.ink,
        marginBottom: "8px",
      }}>
        {market.name}
      </h3>

      <p style={{
        fontFamily: "var(--font-manrope, sans-serif)",
        fontSize: "14px",
        fontStyle: "italic",
        color: C.inkSoft,
        marginBottom: "20px",
      }}>
        {market.subtitle}
      </p>

      <p style={{ ...proseStyle, fontSize: "15px", color: C.inkSoft, marginBottom: "24px" }}>
        <strong style={{ color: C.ink, fontStyle: "normal" }}>The challenge:</strong> {market.challenge}
      </p>

      {/* The description card */}
      <div style={{
        background: C.bgCard,
        border: `1px solid ${C.border}`,
        borderRadius: "12px",
        padding: "24px 28px",
        marginBottom: "20px",
      }}>
        <p style={{ ...proseStyle, fontSize: "16px", margin: 0, lineHeight: 1.7 }}>
          {market.description}
        </p>
      </div>

      {/* Categories */}
      <div style={{ marginBottom: "24px" }}>
        {market.categories.map((cat) => (
          <div key={cat.title}>
            <h4 style={h4Style}>{cat.title}</h4>
            <BulletList items={cat.items.map(item => (
              <><strong>{item.name}</strong> — {item.description}</>
            ))} />
          </div>
        ))}
      </div>

      {/* Analysis */}
      <div style={{ display: "flex", flexDirection: "column", gap: "12px", marginTop: "20px" }}>
        <div style={{ background: "rgba(92,138,110,0.06)", border: `1px solid rgba(92,138,110,0.18)`, borderRadius: "10px", padding: "16px 20px" }}>
          <div style={{ ...h4Style, marginTop: 0, color: "#5C8A6E" }}>What this does well</div>
          <p style={{ ...proseStyle, margin: 0, fontSize: "14.5px", color: C.ink }}>{market.doesWell}</p>
        </div>
        <div style={{ background: "rgba(201,123,92,0.06)", border: `1px solid rgba(201,123,92,0.18)`, borderRadius: "10px", padding: "16px 20px" }}>
          <div style={{ ...h4Style, marginTop: 0, color: "#C97B5C" }}>What to push further</div>
          <p style={{ ...proseStyle, margin: 0, fontSize: "14.5px", color: C.ink }}>{market.pushFurther}</p>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
// Page
// ─────────────────────────────────────────────────────────────────

export default function NeighborhoodDescriptionExamplesPage() {
  return (
    <div className="min-h-screen bg-[#EFEAE0]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(SCHEMA_JSON_LD) }}
      />
      <Header />

      {/* ─────────────── HERO — CREAM ─────────────── */}
      <section className="border-b border-[rgba(20,39,30,0.10)] bg-[#F4F0E8]">
        <div className="mx-auto w-full max-w-[960px] px-6 py-16 sm:py-20 lg:px-8">
          <div className="mx-auto max-w-[720px]">
            <SectionLabel>Reference · Examples gallery</SectionLabel>

            <h1 className="mb-4 font-manrope text-[clamp(28px,4.5vw,48px)] font-medium leading-[1.08] tracking-[0.005em] text-[#14271E]">
              Neighborhood description examples for MLS listings: <em className="not-italic text-[#9A7E50]">12 markets, one framework</em>.
            </h1>

            <p className="mb-6 max-w-[640px] text-[clamp(14px,1.2vw,17px)] leading-[1.6] text-[#4A6B53]">
              Strong neighborhood writing does three things: names specific places that actually exist, captures lifestyle texture that fits the property, and avoids Fair Housing-flagged language. Generic neighborhood content fails on at least one of those three.
            </p>

            <p className="mb-8 max-w-[640px] text-[clamp(14px,1.2vw,17px)] leading-[1.6] text-[#4A6B53]">
              This page shows what that looks like across 12 distinct property contexts — from college-town walkable to mountain-outdoor to working waterfront to revitalizing urban. Each example was generated by Metes using live Google Places API data, edited for voice, and analyzed for what makes the framework work in that specific market.
            </p>

            <p className="text-[13px] font-mono uppercase tracking-[0.08em] text-[rgba(20,39,30,0.55)]">
              Last updated: June 22, 2026 · ~20 minute read
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── TLDR + JUMP TO — EARTH ─────────────── */}
      <section className="bg-[#EFEAE0] py-16 sm:py-20">
        <div className={CONTENT}>
          <div className={READING}>
            <div style={{
              background: C.bgCard,
              border: `1px solid ${C.border}`,
              borderRadius: "12px",
              padding: "28px",
              marginBottom: "32px",
            }}>
              <div className="mb-3 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-[#9A7E50]">
                TLDR
              </div>
              <p style={proseStyle}>
                The framework: anchor in real, named, verifiable places. Structure around lifestyle moments (morning, weekend, evening). Capture what makes the neighborhood specifically itself. Get all three right and you have neighborhood content that helps the listing, defends against Fair Housing exposure, and reads as written by someone who knows the area.
              </p>
              <p style={{ ...proseStyle, marginBottom: 0 }}>
                The point isn&apos;t to copy the examples. It&apos;s to learn the framework that produces them, so you can describe any neighborhood you list with the same structural strength.
              </p>
            </div>

            <div className="mb-3 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-[#9A7E50]">
              Jump to
            </div>
            <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
              {[
                { id: "why-fail", label: "Why most neighborhood descriptions fail" },
                { id: "methodology", label: "How these examples were generated" },
                { id: "examples", label: "The 12 markets" },
                { id: "patterns", label: "Patterns across all 12" },
                { id: "hard-cases", label: "When neighborhoods genuinely lack character" },
                { id: "faq", label: "Common questions" },
              ].map(({ id, label }) => (
                <li key={id}>
                  <a href={`#${id}`} style={{
                    fontFamily: "var(--font-manrope, sans-serif)",
                    fontSize: "14px",
                    color: C.forest,
                    textDecoration: "underline",
                    textDecorationColor: C.gold,
                    textUnderlineOffset: "3px",
                  }}>
                    {label}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* ─────────────── WHY MOST FAIL — CREAM ─────────────── */}
      <section id="why-fail" className="border-t border-[rgba(20,39,30,0.10)] bg-[#F4F0E8] py-16 sm:py-20">
        <div className={CONTENT}>
          <div className={READING}>
            <SectionLabel>The problem</SectionLabel>
            <h2 style={h2Style}>Why most neighborhood descriptions fail</h2>

            <p style={proseStyle}>
              Open any MLS in any market and pull 50 listing descriptions. Most won&apos;t mention the neighborhood at all. The ones that do almost always fall into one of three patterns:
            </p>

            <p style={proseStyle}>
              <strong>Generic boilerplate:</strong> &ldquo;Vibrant community with excellent schools and easy access to dining and shopping.&rdquo; Says nothing. Could describe any neighborhood. The agent wrote it because they felt they had to write something.
            </p>

            <p style={proseStyle}>
              <strong>Real estate cliche:</strong> &ldquo;Established neighborhood featuring tree-lined streets and a charming small-town feel.&rdquo; Slightly more specific but still interchangeable. Could be a suburb in any state.
            </p>

            <p style={proseStyle}>
              <strong>Demographic shorthand that triggers Fair Housing risk:</strong> &ldquo;Family-friendly community perfect for young professionals.&rdquo; Both phrases are prohibited language per HUD enforcement. First-offense civil penalty is $25,597.
            </p>

            <p style={proseStyle}>
              The agents writing these descriptions aren&apos;t lazy. They&apos;re working under deadline with no framework for what makes a neighborhood description actually work. The default falls back to filler.
            </p>

            <h3 style={h3Style}>What strong neighborhood writing does</h3>

            <p style={proseStyle}>
              A neighborhood description that actually helps a listing — and stays legally defensible — does three things:
            </p>

            <BulletList items={[
              <><strong>Names specific places that exist.</strong> Real businesses, real parks, real institutions. Buyers can verify what&apos;s named. Specific names anchor the description in reality and signal that the agent knows the area.</>,
              <><strong>Captures texture that fits the property.</strong> Not generic adjectives. Specific lifestyle moments. The kind of morning, the kind of weekend, the kind of evening that this neighborhood enables.</>,
              <><strong>Avoids Fair Housing-flagged language.</strong> No &ldquo;perfect for families.&rdquo; No &ldquo;great for young professionals.&rdquo; No &ldquo;walking distance&rdquo; as a general descriptor. The complete reference is in the <Link href="/learn/fair-housing-language-mls-listings" style={{ color: C.forest, textDecoration: "underline", textDecorationColor: C.gold, textUnderlineOffset: "3px" }}>Fair Housing language guide</Link>.</>,
            ]} />

            <p style={proseStyle}>
              Every example below does all three. Some better than others — we&apos;ll be honest about where each one shines and where it could be polished further.
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── METHODOLOGY — EARTH ─────────────── */}
      <section id="methodology" className="bg-[#EFEAE0] py-16 sm:py-20">
        <div className={CONTENT}>
          <div className={READING}>
            <div className="mb-4 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-[#9A7E50]">
              <Sparkles className="h-3 w-3" strokeWidth={2} />
              Methodology
            </div>
            <h2 style={h2Style}>How these examples were generated</h2>

            <p style={proseStyle}>
              Each of the 12 examples below was generated by <Link href="/tools/neighborhood-guide-generator" style={{ color: C.forest, textDecoration: "underline", textDecorationColor: C.gold, textUnderlineOffset: "3px" }}>Metes&apos; free neighborhood guide tool</Link>. The tool takes a property address as input and returns a structured neighborhood description.
            </p>

            <p style={proseStyle}>
              Under the hood: the tool queries Google Places API at the time of generation, returning verified businesses, parks, schools, and amenities currently operating near the address. The LLM that produces the description works only from that returned data — it does not research the address from training data, and it does not invent place names, attributes, or claims it can&apos;t ground in the API response.
            </p>

            <p style={proseStyle}>
              <strong>Why this matters:</strong> general-purpose tools like ChatGPT generate neighborhood content from training data, which has a knowledge cutoff and produces fabrication rates as high as 31.4% in real-world use (covered in detail in <Link href="/compare/metes-vs-chatgpt" style={{ color: C.forest, textDecoration: "underline", textDecorationColor: C.gold, textUnderlineOffset: "3px" }}>Metes vs ChatGPT</Link>). The fruit-trees fabrication case from Florida Realtors — where a ChatGPT-generated listing invented a grove of fruit trees that didn&apos;t exist on the property — is the canonical example of the failure mode. Constraining the LLM to verified API data prevents that class of error.
            </p>

            <p style={proseStyle}>
              <strong>What we did to each output for this page:</strong> light editorial polish. We removed a few generic AI-prose patterns (&ldquo;balanced pace of life,&rdquo; &ldquo;embracing the best of,&rdquo; &ldquo;high-quality&rdquo; used as a filler adjective) and tightened the voice where it veered toward formula. We did not add new places, change which places were referenced, or invent attributes the API didn&apos;t return. Every named business, park, and institution in the examples below is real and was returned by the API at generation time.
            </p>

            <p style={proseStyle}>
              The honest read: Metes produces strong baseline neighborhood content. Editorial polish improves it further. The framework below works regardless of who&apos;s writing — the agent themselves, an AI tool, or a hybrid workflow.
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── THE 12 MARKETS — CREAM, WIDER ─────────────── */}
      <section id="examples" className="border-t border-[rgba(20,39,30,0.10)] bg-[#F4F0E8] py-16 sm:py-20">
        <div className={CONTENT}>
          <div className={READING}>
            <SectionLabel>The examples</SectionLabel>
            <h2 style={h2Style}>The 12 markets</h2>
            <p style={{ ...proseStyle, marginBottom: "48px" }}>
              Twelve property contexts, each demonstrating a different neighborhood description challenge. Read in order or skip to a category that matches what you&apos;re listing.
            </p>

            {MARKETS.map((market) => (
              <MarketBlock key={market.slug} market={market} />
            ))}
          </div>
        </div>
      </section>

      {/* ─────────────── PATTERNS — FOREST DARK ─────────────── */}
      <section id="patterns" className="relative overflow-hidden bg-[#14271E] py-20 sm:py-24">
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            backgroundImage:
              "linear-gradient(rgba(184,153,104,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(184,153,104,0.06) 1px, transparent 1px)",
            backgroundSize: "32px 32px",
          }}
        />
        <div className={`relative ${CONTENT}`}>
          <div className={READING}>
            <div className="mb-4 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.14em] text-[#D9C49C]">
              <Compass className="h-3 w-3" strokeWidth={2} />
              The framework
            </div>
            <h2 style={{ ...h2Style, color: C.creamWarm }}>Patterns across all 12</h2>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              Read the 12 examples back to back and the framework that produces strong neighborhood writing comes into focus. Three things show up everywhere the output succeeds, and three things show up where it falls short.
            </p>

            <h3 style={{ ...h3Style, color: C.creamWarm }}>What the strong moments share</h3>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>1. Specific named places do most of the work.</strong> The Belted Goat, Pip&apos;s Original Doughnuts, Sweet Potato Sensations, the Teddy Bear Statues, Peets Hill. Specific names anchor everything. A reader can verify them, an agent looks knowledgeable for knowing them, and a buyer evaluating the neighborhood from out of state gets concrete signal about what&apos;s there.
            </p>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>2. Lifestyle structure follows real rhythms.</strong> Morning → weekend → evening. Or: everyday → recreation → dining → wellness. The structure mirrors how buyers actually evaluate whether a neighborhood fits them — they imagine their daily life happening here. The category structure makes that imagining easier.
            </p>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>3. Each named place earns its mention.</strong> Lewis Barbecue is in the Charleston description because it&apos;s a specific Charleston dining destination, not because every neighborhood needs a barbecue mention. Mitsuwa is in the Plano description because it&apos;s a regional anomaly worth naming. The specific over the generic, every time.
            </p>

            <h3 style={{ ...h3Style, color: C.creamWarm }}>Where neighborhood descriptions get weaker</h3>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>1. Generic openers signal AI prose.</strong> Phrases like &ldquo;centers on a balance of,&rdquo; &ldquo;embracing the best of,&rdquo; &ldquo;defined by,&rdquo; &ldquo;a balanced pace of life&rdquo; appear across many outputs and across many human-written listing descriptions. They&apos;re the linguistic fingerprint of writing-without-a-specific-point. Strong neighborhood writing earns its opening sentence — it leads with something specific to this neighborhood, not a template applied to any neighborhood.
            </p>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>2. Per-place descriptions blur into one another.</strong> When a yoga studio is described as &ldquo;a dedicated studio offering challenging classes&rdquo; and a coffee shop as &ldquo;an independent shop offering expertly crafted roasts,&rdquo; the descriptions become interchangeable. Strong per-place descriptions reference what makes THIS place distinct — its history, its specific signature item, its role in the community.
            </p>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              <strong style={{ color: C.gold }}>3. The neighborhood&apos;s character doesn&apos;t always come through.</strong> Bozeman&apos;s outdoor and mountain identity, Asheville&apos;s brewery scene, Annapolis&apos;s maritime culture — sometimes these surface, sometimes they don&apos;t. The strongest descriptions capture not just what&apos;s nearby but what kind of life the neighborhood enables.
            </p>

            <h3 style={{ ...h3Style, color: C.creamWarm }}>The framework, restated</h3>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              Strong neighborhood writing does three things together:
            </p>

            <ul style={{ listStyle: "none", padding: 0, margin: "0 0 16px 0", display: "flex", flexDirection: "column", gap: "10px" }}>
              {[
                <><strong style={{ color: C.gold }}>Anchors in real, named, verifiable places.</strong> No invented businesses, no generic boilerplate.</>,
                <><strong style={{ color: C.gold }}>Structures around lifestyle moments.</strong> Morning, weekend, evening. Everyday, outdoor, dining, wellness. The reader imagines themselves living there.</>,
                <><strong style={{ color: C.gold }}>Captures the neighborhood&apos;s specific character.</strong> Not generic adjectives. Something that distinguishes this neighborhood from a similarly-sized neighborhood three states away.</>,
              ].map((item, i) => (
                <li key={i} style={{ paddingLeft: "20px", position: "relative", fontFamily: "var(--font-manrope, sans-serif)", fontSize: "16px", lineHeight: 1.7, color: "rgba(244,240,232,0.85)" }}>
                  <span style={{ position: "absolute", left: "4px", color: C.gold, fontWeight: 600 }}>•</span>
                  {item}
                </li>
              ))}
            </ul>

            <p style={{ ...proseStyle, color: "rgba(244,240,232,0.85)" }}>
              Get all three right and you have neighborhood content that helps the listing, defends against Fair Housing exposure, and reads as written by someone who knows the area.
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── HARD CASES — CREAM ─────────────── */}
      <section id="hard-cases" className="bg-[#F4F0E8] py-16 sm:py-20">
        <div className={CONTENT}>
          <div className={READING}>
            <SectionLabel>When it gets hard</SectionLabel>
            <h2 style={h2Style}>When neighborhoods genuinely lack character</h2>

            <p style={proseStyle}>
              Not every neighborhood has obvious texture. Some are new-construction subdivisions with limited surrounding commercial density. Some are working-class areas where the Places API returns few results because the local economy doesn&apos;t generate the same density of restaurants and yoga studios that an affluent suburb produces. Some are genuinely undifferentiated.
            </p>

            <p style={proseStyle}>
              When the underlying neighborhood lacks rich texture, the strong move is to describe what&apos;s actually there honestly, then anchor the description on the property itself — the lot, the home&apos;s features, what makes the specific property worth listing. Forcing texture that doesn&apos;t exist produces the generic-boilerplate failure mode.
            </p>

            <p style={proseStyle}>
              The Fair Housing constraint also applies here: even neighborhoods that lack obvious commercial character must be described without resorting to demographic shorthand. &ldquo;Quiet neighborhood&rdquo; is coded language. &ldquo;Established neighborhood&rdquo; is acceptable. The specific language matters as much as the underlying claim. The full reference is in the <Link href="/learn/fair-housing-language-mls-listings" style={{ color: C.forest, textDecoration: "underline", textDecorationColor: C.gold, textUnderlineOffset: "3px" }}>Fair Housing language guide</Link>.
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── FAQ — EARTH ─────────────── */}
      <section id="faq" className="border-t border-[rgba(20,39,30,0.10)] bg-[#EFEAE0] py-20 sm:py-24">
        <div className={CONTENT}>
          <div className={READING}>
            <SectionLabel>Common questions</SectionLabel>
            <h2 style={h2Style}>Common questions</h2>

            <div style={{ display: "flex", flexDirection: "column", gap: "14px", marginTop: "24px" }}>
              {[
                {
                  q: "How long should a neighborhood description be?",
                  a: "There's no fixed length. A neighborhood section within an MLS description typically runs 75-150 words; a standalone neighborhood guide on a listing page or microsite can run 300-500 words. The principle is the same: every sentence should add specific information. If a sentence could describe any neighborhood, it shouldn't be in the description.",
                },
                {
                  q: "What should I include in a neighborhood description for an MLS listing?",
                  a: "The strongest neighborhood descriptions reference 3-5 specific named places (coffee shops, restaurants, parks, stores), 1-2 outdoor or recreation features, and any specific lifestyle texture that makes the neighborhood distinctive. Skip generic adjectives like 'vibrant,' 'welcoming,' or 'family-oriented' — they don't add information and 'family-oriented' specifically violates Fair Housing rules.",
                },
                {
                  q: "What words to avoid in neighborhood descriptions?",
                  a: "HUD-flagged language to avoid includes: 'perfect for families,' 'great for young professionals,' 'family-friendly,' 'walking distance' as a general descriptor without specific distance, 'safe neighborhood,' 'quiet' as a coded character descriptor, 'exclusive,' and others. First-offense civil penalty for Fair Housing violations is $25,597.",
                },
                {
                  q: "Should I describe schools in MLS listings?",
                  a: "Per HUD's April 2026 Dear Colleague letter, agents may share factual school information (district names, ratings from sources like GreatSchools) with buyers, as long as the information is shared consistently and not used to direct buyers toward or away from neighborhoods based on protected class characteristics. Subjective descriptors like 'top schools' remain risky; specific data points (GreatSchools rating, district name) are safer.",
                },
                {
                  q: "Should I name local businesses in listing descriptions?",
                  a: "Yes — naming specific businesses is generally safe and strongly improves the quality of neighborhood writing. The constraints: the businesses should actually exist (no fabrication), they should genuinely be near the property, and the descriptions should be factual rather than promotional. 'Whole Foods Market' is fine; 'the best grocery store in the area' is subjective and weaker.",
                },
                {
                  q: "How is writing about a small town different from writing about a city?",
                  a: "Smaller markets typically have lower commercial density, which means fewer named places to anchor the description. The strong move is to write fewer places more deeply rather than padding the description with thin mentions. A single well-described local institution is stronger than a list of five generic descriptors. Also: in smaller markets, mentioning context (the named neighborhood, the named region) carries more weight because readers may be evaluating the area from out of state.",
                },
                {
                  q: "Can AI write neighborhood descriptions accurately?",
                  a: "AI tools that work from training data alone (general-purpose tools like ChatGPT) routinely fabricate local businesses, parks, and amenities. Real-world LLM hallucination rates run 31.4% in complex domains. Tools that constrain the LLM to verified data sources (like the Google Places API) produce materially more accurate output. AI-generated neighborhood content has come a long way, but it benefits from light editorial polish to remove generic AI prose patterns.",
                },
                {
                  q: "What's the Fair Housing rule for neighborhood descriptions?",
                  a: "The Fair Housing Act prohibits language in real estate advertising that indicates preference based on race, color, religion, sex, familial status, disability, or national origin. For neighborhood descriptions specifically, the most common violations involve familial status ('perfect for families') and disability ('walking distance'). The April 2026 HUD guidance clarified that factual school and crime data may be shared consistently.",
                },
              ].map(({ q, a }, i) => (
                <details
                  key={i}
                  style={{
                    borderRadius: "12px",
                    border: `1px solid ${C.border}`,
                    background: C.bgCard,
                    padding: "20px 24px",
                  }}
                >
                  <summary style={{
                    fontFamily: "var(--font-manrope, sans-serif)",
                    fontSize: "16px",
                    fontWeight: 500,
                    color: C.ink,
                    cursor: "pointer",
                    listStyle: "none",
                    letterSpacing: "-0.005em",
                  }}>
                    {q}
                  </summary>
                  <div style={{ marginTop: "14px", fontSize: "14.5px", lineHeight: 1.7, color: C.inkSoft }}>
                    {a}
                  </div>
                </details>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ─────────────── SOURCES — CREAM ─────────────── */}
      <section className="bg-[#EFEAE0] py-10">
        <div className={CONTENT}>
          <div className={READING}>
            <p style={{
              fontFamily: "var(--font-jetbrains, monospace)",
              fontSize: "12px",
              lineHeight: 1.6,
              color: C.muted,
              textAlign: "center",
              fontStyle: "italic",
            }}>
              Sources: Google Places API data (queried at generation for each example); HUD Office of Fair Housing and Equal Opportunity penalty schedules (24 CFR § 180.671, March 2024 adjustment); Florida Realtors Magazine, &ldquo;The Real Reasons AI Can&apos;t Replace Real Estate Professionals&rdquo; (2024); JMIR Comparative Analysis of LLM Hallucination Rates (peer-reviewed, 2024). This reference is informational and not legal advice.
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── FINAL CTA — DARK FOREST ─────────────── */}
      <section className="relative overflow-hidden bg-[#14271E] py-20 sm:py-24">
        <div
          className="pointer-events-none absolute inset-0"
          style={{
            backgroundImage:
              "linear-gradient(rgba(184,153,104,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(184,153,104,0.06) 1px, transparent 1px)",
            backgroundSize: "32px 32px",
          }}
        />
        <div className={`relative ${CONTENT}`}>
          <div style={{ maxWidth: "720px" }}>
            <SectionLabel light>Try it on your next listing</SectionLabel>
            <h2 className="mb-5 font-manrope text-[clamp(28px,4vw,42px)] font-medium leading-[1.1] tracking-[0.005em] text-[#F4F0E8]">
              Strong neighborhood writing is <em className="not-italic text-[#B89968]">a small craft with a clear structure</em>.
            </h2>
            <p className="mb-8 max-w-[600px] text-[clamp(15px,1.3vw,17px)] leading-[1.6] text-[rgba(244,240,232,0.78)]">
              Name specific places. Organize around lifestyle moments. Capture what makes the neighborhood specifically itself. The framework works regardless of how the writing happens — agent-written, AI-generated, or hybrid.
            </p>
            <div className="flex flex-wrap gap-3">
              <Link
                href="/tools/neighborhood-guide-generator"
                className="inline-flex items-center gap-2 rounded-[9px] bg-[#B89968] px-7 py-3.5 font-manrope text-[14px] font-medium text-[#14271E] no-underline transition-colors hover:bg-[#9A7E50] hover:text-[#F4F0E8]"
              >
                Try the free neighborhood guide tool
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
              <Link
                href="/"
                className="inline-flex items-center gap-2 rounded-[9px] border border-[rgba(244,240,232,0.3)] bg-transparent px-7 py-3.5 font-manrope text-[14px] font-medium text-[#F4F0E8] no-underline hover:border-[rgba(244,240,232,0.6)]"
              >
                See the full Metes kit — $35
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}